### ISSUE TITLE
Requirements for the layout of rosters

### ISSUE THREAD

**Issue by xfq** [w3c/clreq#268]
Although it is not a high priority, we can write about the layout requirements of rosters (人员名册), because this requirement cannot be easily implemented using HTML and CSS at present. For example, if we specify the column width as "three characters", if there are only two characters, there is spacing with the same width of a ideographic space in the middle; if the name is too long, the subsequent names start from the next column, etc. This kind of list is common in traditional media.

虽然不是高优先级，不过我们可以写一下人员名册的排版需求，因为这个需求目前也无法使用HTML和CSS简单地实现。比如以「占三格」为栏宽，如果只有两个字，则中间空一个汉字宽；如果人名过长，则其后的姓名从下一栏开始等。

**Comment by xfq** [comment]
Here is an example:

<img width="500" alt="Image" src="https://github.com/user-attachments/assets/591ffec5-ace3-4cbd-9090-7460143831b1" />

The second line is not aligned correctly, but it reflects the general meaning.

**Comment by xfq** [comment]
@fantasai @frivoal How do you think this should be achieved?

**Comment by frivoal** [comment]
A quick attempt at copy and pasting the text from the image above gives

```
李明
孙墨轩
刘梦琪
休伯特·布莱因
赵琪
张伟强
张晨光
刘梦琪
林小雨
李思宇
陈子轩
钱欣然
王浩然
赵雨欣
```

**Comment by xfq** [comment]
Thanks Florian, I fixed a few typos in that list.

**Comment by xfq** [comment]
Discussion in TPAC 2025: https://www.w3.org/2025/11/09-i18n-minutes.html#3b13

**Comment by AmeroHan** [comment]
Only the requirement that "if the name is too long, the subsequent names start from the next column" is unable to implement using HTML and CSS.

```css
.roster {
  display: grid;
  grid-template-columns: repeat(3, 3ic);
  gap: 0.5ic 1ic;
  padding: 0;
  margin: 2ic;

  li {
    display: block;
    text-align-last: justify;
    background-color: aquamarine;
  }
}
```

```html
<ul class="roster">
  <li>李明</li>
  <li>孙墨轩</li>
  <li>刘梦琪</li>
  <li>休伯特·布莱因</li>
  <li>赵琪</li>
  <li>张伟强</li>
  <li>张晨光</li>
  <li>刘梦琪</li>
  <li>林小雨</li>
  <li>李思宇</li>
  <li>陈子轩</li>
  <li>钱欣然</li>
  <li>王浩然</li>
  <li>赵雨欣</li>
</ul>
```

<img width="389" height="399" alt="Image" src="https://github.com/user-attachments/assets/859901de-8d55-4138-bded-5af1298685e5" />

There should be an approach for CSS in the future to make cells automatically occupy 2 or more columns when their `max-content` exceed column width.

**Comment by AmeroHan** [comment]
Flex can be used if your gap has a fixed length, which means `justify-content` cannot be `space-*`.

```css
.roster {
  --row-gap: 0.5ic;
  --column-gap: 1ic;
  --column-width: 3ic;
  --column-count: 3;
  display: flex;
  flex-wrap: wrap;
  width: calc(
    var(--column-width) * var(--column-count)
    + var(--column-gap) * (var(--column-count) - 1)
  );
  gap: var(--row-gap) var(--column-gap);
  padding: 0;
  margin: 2ic;

  li {
    display: block;
    text-align-last: justify;
    background-color: aquamarine;
    width: calc-size(
      max-content,
      var(--column-width)
      + round(
        up,
        size - var(--column-width),
        var(--column-width) + var(--column-gap)
      )
    );
  }
}
```

<img width="411" height="331" alt="Image" src="https://github.com/user-attachments/assets/ee8a830e-f14e-47ee-b3d8-7a5ba9b4cf85" />

[Interactive test](https://w3c.github.io/i18n-tests/exploratory/index.html?text=%3Cul%20class%3D%22roster%22%3E%0A%20%20%3Cli%3E%E6%9D%8E%E6%98%8E%3C%2Fli%3E%0A%20%20%3Cli%3E%E5%AD%99%E5%A2%A8%E8%BD%A9%3C%2Fli%3E%0A%20%20%3Cli%3E%E5%88%98%E6%A2%A6%E7%90%AA%3C%2Fli%3E%0A%20%20%3Cli%3E%E4%BC%91%E4%BC%AF%E7%89%B9%C2%B7%E5%B8%83%E8%8E%B1%E5%9B%A0%3C%2Fli%3E%0A%20%20%3Cli%3E%E8%B5%B5%E7%90%AA%3C%2Fli%3E%0A%20%20%3Cli%3E%E5%BC%A0%E4%BC%9F%E5%BC%BA%3C%2Fli%3E%0A%20%20%3Cli%3E%E5%BC%A0%E6%99%A8%E5%85%89%3C%2Fli%3E%0A%20%20%3Cli%3E%E5%88%98%E6%A2%A6%E7%90%AA%3C%2Fli%3E%0A%20%20%3Cli%3E%E6%9E%97%E5%B0%8F%E9%9B%A8%3C%2Fli%3E%0A%20%20%3Cli%3E%E6%9D%8E%E6%80%9D%E5%AE%87%3C%2Fli%3E%0A%20%20%3Cli%3E%E9%99%88%E5%AD%90%E8%BD%A9%3C%2Fli%3E%0A%20%20%3Cli%3E%E9%92%B1%E6%AC%A3%E7%84%B6%3C%2Fli%3E%0A%20%20%3Cli%3E%E7%8E%8B%E6%B5%A9%E7%84%B6%3C%2Fli%3E%0A%20%20%3Cli%3E%E8%B5%B5%E9%9B%A8%E6%AC%A3%3C%2Fli%3E%0A%3C%2Ful%3E&css=.roster%20%7B%0A%20%20--row-gap%3A%200.5ic%3B%0A%20%20--column-gap%3A%201ic%3B%0A%20%20--column-width%3A%203ic%3B%0A%20%20display%3A%20flex%3B%0A%20%20flex-wrap%3A%20wrap%3B%0A%20%20gap%3A%20var(--row-gap)%20var(--column-gap)%3B%0A%20%20padding%3A%200%3B%0A%20%20margin%3A%200%3B%0A%0A%20%20li%20%7B%0A%20%20%20%20display%3A%20block%3B%0A%20%20%20%20text-align-last%3A%20justify%3B%0A%20%20%20%20width%3A%20calc-size(%0A%20%20%20%20%20%20max-content%2C%0A%20%20%20%20%20%20var(--column-width)%0A%20%20%20%20%20%20%2B%20round(%0A%20%20%20%20%20%20%20%20up%2C%0A%20%20%20%20%20%20%20%20size%20-%20var(--column-width)%2C%0A%20%20%20%20%20%20%20%20var(--column-width)%20%2B%20var(--column-gap)%0A%20%20%20%20%20%20)%0A%20%20%20%20)%3B%0A%20%20%7D%0A%7D&lang=zh&fontSize=36&width=420&height=320&a=&i=)
