### ISSUE TITLE
兩點意見…

### ISSUE THREAD

**Issue by c933103** [w3c/clreq#82]
- readme裡面的principle譯成中文好像欠理想？
- 文檔中提到簡體轉繁體存在一對多，是不是也應提及繁體轉簡體也有一對多呢？

p.s.雖然好像不應該在這裡問但能順便問一下現在用css如何表示專名號/書名號嗎？

**Comment by ethantw** [comment]
> principle譯成中文好像欠理想？

已修正為「原則」（原作「條約」）。

> 是不是也應提及繁體轉簡體也有一對多呢？

疏忽了，我等會來修正。

> 能順便問一下現在用css如何表示專名號/書名號嗎？

參考：http://www.w3.org/TR/css-text-decor-3/#text-decoration-line-property

``` html
<html lang="zh-Hant">
  <u>專名號</u>
  <cite>甲式書名號（波浪底線）</cite>
```

``` css
u:lang(zh),
cite:lang(zh) {
  text-decoration: underline;
  text-decoration-line: underline;
  text-decoration-skip: edges;
}

u:lang(zh) {
  text-decoration-style: solid;
}

cite:lang(zh) {
  text-decoration-style: wavy;
}
```

目前多數瀏覽器尚不支援CSS Text Level 3更新後的`text-decoration`屬性。
